# Generated by Django 3.0.4 on 2020-03-08 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='booking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(default='')),
                ('start', models.DateTimeField(default='')),
                ('end', models.DateTimeField(default='')),
            ],
        ),
    ]
