# Generated by Django 2.2.11 on 2020-03-08 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('createbooking', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='name',
            new_name='nam',
        ),
    ]
