# Generated by Django 2.2.11 on 2020-03-08 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('createbooking', '0002_auto_20200308_1814'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='booking',
            new_name='bookingmodel',
        ),
        migrations.RenameField(
            model_name='bookingmodel',
            old_name='nam',
            new_name='name',
        ),
    ]
